### ISSUE TITLE
Works With Ubuntu Server 21.04 [WIP]

### ISSUE THREAD

**Issue by Dracozny** [64kramsystem/zfs-installer#237]
Currently testing but so far it seems to work with 21.04. I did spot some snap breakage but not sure if that is related just yet.

**Comment by 64kramsystem** [comment]
Hello! Thanks for the help :) Let me know once you have a conclusion; I'll then give a double check, and officially add the support :)

**Comment by Dracozny** [comment]
After rebooting it presented some snap errors while booting. The resolution there was to complete apt update && apt upgrade this resulted in outdated services which a few of them would restart successfully but a final restart needed to happen to clean it up.  I repeated the test on a second system that I haven't installed anything else on just yet. The first system is still running but I did not do the reboot with it yet so it is giving me an error in dmesg about core18_1997.snap, lxd_20037.snap and snapd_11588.snap are unable to open blockdev. The second system presents no such errors after the above steps. 
If there is anything specific you want to look at let me know.
[installer-journal.txt](https://github.com/64kramsystem/zfs-installer/files/7222969/installer-journal.txt)

**Comment by 64kramsystem** [comment]
Thanks for the feedback. I'll investigate it. I'll be able to do this in October, due to work on two difficult projects, but don't worry, I won't forget :) Thanks again for the participation :)

**Comment by 64kramsystem** [comment]
Can you post the zfs installer logs? They help significantly in debugging and reproducing the issue.

**Comment by Dracozny** [comment]
Ok, after double checking your script (unless I missed something) I realized that it would be on the Live Install until reboot. I will have to redo the test to capture the log.

**Comment by 64kramsystem** [comment]
Hello!

So, I've done some testing, in order to see if I could spot something obvious, but I got bad news :grimacing: 

On my first attempt, VirtualBox hung during installation (!!). This is actually irrelevant, but well... :smile: 

Anyway, on the second attempt, after installing the O/S, during the rsync stage, the installer failed with very obscure errors.

Now, the problem is that 21.04 will soon be EOL, as it's not an LTS, and 21.10 is relatively close (approximately less than 4 weeks), so any effort to make it work may be wasted - the errors that both you and I faced are both quite obscure. Additionally, 21.04 is not to be used in production systems, so the audience is small/short-lived.

I'm open to any findings, if you have something, of course :)

**Comment by Dracozny** [comment]
considering the EOL, I think you are right and we can close. I didn't even realize 21.10 is due to be out soon. I will look into testing 21.10. I can make due with my current installs until then. 
I would have to reinstall on one of the systems just to capture the logs. I would suggest a fix if possible and that would be to save the logs to the writable partition of the USB with the Ubuntu Installer logs. That would make autopsy of a success or failure easier. 

Ubuntu 21.10 Beta: Sept 23, 2021
Kernel Freeze: Sept 30, 2021
Release Candidate: Oct 7, 2021
Released on October 14, 2021

**Comment by 64kramsystem** [comment]
> I would suggest a fix if possible and that would be to save the logs to the writable partition of the USB with the Ubuntu Installer logs. That would make autopsy of a success or failure easier.

This is a very good suggestion. I've created [an issue](https://github.com/64kramsystem/zfs-installer/issues/238) for it.
